#!/usr/bin/env bash
# Regenerate the Wants= drop-in for quantlab-tick.service from what is actually
# under paper_runs/, then tell systemd. Run it after every `paper.py start` and
# every `paper.py stop`; the tick polls exactly what this file says and nothing
# else, so a run that was started but not synced is a run that is not polled.
#
#     deploy/sync-tick.sh                 # checkout at /root/tradingview-mcp
#     QUANTLAB_ROOT=/home/me/tradingview-mcp deploy/sync-tick.sh
#
# Idempotent: writing the same list twice changes nothing but the daemon-reload.
set -euo pipefail

ROOT="${QUANTLAB_ROOT:-/root/tradingview-mcp}"
PY="${QUANTLAB_PYTHON:-$ROOT/env/bin/python}"
DROPIN_DIR=/etc/systemd/system/quantlab-tick.service.d
DROPIN="$DROPIN_DIR/wants.conf"

if [ ! -x "$PY" ]; then
    echo "sync-tick: no python at $PY — set QUANTLAB_ROOT or QUANTLAB_PYTHON" >&2
    exit 1
fi

# ask the code, not the filesystem: it knows about STOPPED markers and run ids.
# It also drops any run dir whose name cannot be a systemd instance name
# (RUN_ID_RE in paper.py) and says so on stderr, which passes through below —
# no second check here, the line is written as given.
wants="$(cd "$ROOT" && "$PY" paper.py tick-wants)"
case "$wants" in
    Wants=*) ;;
    *) echo "sync-tick: unexpected output from paper.py tick-wants: $wants" >&2; exit 1 ;;
esac

mkdir -p "$DROPIN_DIR"
tmp="$(mktemp "$DROPIN_DIR/.wants.conf.XXXXXX")"
printf '# generated by deploy/sync-tick.sh from `paper.py tick-wants` — do not edit\n[Unit]\n%s\n' "$wants" > "$tmp"
chmod 644 "$tmp"
mv -f "$tmp" "$DROPIN"

systemctl daemon-reload

echo "wrote $DROPIN:"
sed 's/^/    /' "$DROPIN"
echo
echo "systemd now sees:"
systemctl show quantlab-tick.service -p Wants --value | tr ' ' '\n' | sed 's/^/    /'
